antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'kafka'

site:
  title: Spring Kafka
  url: https://docs.spring.io/spring-kafka/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-kafka
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [ main,'({3..9}).+({0..9}).x', '!(3.0.x)' ]
    tags: [ 'v({3..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(v3.0.+({0..9})?(-{RC,M}+({0..9})))' ]
    start_path: spring-kafka-docs/src/main/antora
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-kafka
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
  - '@springio/asciidoctor-extensions/javadoc-extension'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.15/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
