[[quick-tour]]
=== Quick Tour

Prerequisites: You must install and run Apache Kafka.
Then you must put the spring-kafka JAR and all of its dependencies on your class path.
The easiest way to do that is to declare a dependency in your build tool.

If you are not using Spring Boot, declare the `spring-kafka` jar as a dependency in your project.

.Maven
====
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.springframework.kafka</groupId>
  <artifactId>spring-kafka</artifactId>
  <version>{project-version}</version>
</dependency>
----
====

.Gradle
====
[source,groovy,subs="+attributes"]
----
compile 'org.springframework.kafka:spring-kafka:{project-version}'
----
====

IMPORTANT: When using Spring Boot, (and you haven't used start.spring.io to create your project), omit the version and Boot will automatically bring in the correct version that is compatible with your Boot version:

.Maven
====
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.springframework.kafka</groupId>
  <artifactId>spring-kafka</artifactId>
</dependency>
----
====

.Gradle
====
[source,groovy,subs="+attributes"]
----
compile 'org.springframework.kafka:spring-kafka'
----
====

However, the quickest way to get started is to use https://start.spring.io[start.spring.io] (or the wizards in Spring Tool Suits and Intellij IDEA) and create a project, selecting 'Spring for Apache Kafka' as a dependency.

[[compatibility]]
==== Compatibility

This quick tour works with the following versions:

* Apache Kafka Clients 2.7.0
* Spring Framework 5.3.x
* Minimum Java version: 8

==== Getting Started

The simplest way to get started is to use https://start.spring.io[start.spring.io] (or the wizards in Spring Tool Suits and Intellij IDEA) and create a project, selecting 'Spring for Apache Kafka' as a dependency.
Refer to the https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-kafka[Spring Boot documentation] for more information about its opinionated auto configuration of the infrastructure beans.

Here is a minimal consumer application.

===== Spring Boot Consumer App

.Application
====
[source, java]
----
include::{code-examples}/started/consumer/Application.java[tag=startedConsumer]
----
====

.application.properties
====
[source, properties]
----
spring.kafka.consumer.auto-offset-reset=earliest
----
====

The `NewTopic` bean causes the topic to be created on the broker; it is not needed if the topic already exists.

===== Spring Boot Producer App

.Application
====
[source, java]
----
include::{code-examples}/started/producer/Application.java[tag=startedProducer]
----
====

==== With Java Configuration (No Spring Boot)

IMPORTANT: Spring for Apache Kafka is designed to be used in a Spring Application Context.
For example, if you create the listener container yourself outside of a Spring context, not all functions will work unless you satisfy all of the `...Aware` interfaces that the container implements.

Here is an example of an application that does not use Spring Boot; it has both a `Consumer` and `Producer`.

.Without Boot
====
[source,java]
----
include::{code-examples}/started/noboot/Sender.java[tag=startedNoBootSender]

include::{code-examples}/started/noboot/Listener.java[tag=startedNoBootListener]

include::{code-examples}/started/noboot/Config.java[tag=startedNoBootConfig]
----
====

As you can see, you have to define several infrastructure beans when not using Spring Boot.
